"""empty message

Revision ID: 6fa9443646a9
Revises: c5a198d95bd2
Create Date: 2022-09-19 13:52:44.168562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fa9443646a9'
down_revision = 'c5a198d95bd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'type')
    # ### end Alembic commands ###
